version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    labels: ["S1-pleasereview", "dependencies", "automated-pr"]
    # Handle updates for crates from github.com/paritytech/substrate manually.
    ignore:
      - dependency-name: "substrate-*"
      - dependency-name: "polkadot-*"
      - dependency-name: "sc-*"
      - dependency-name: "sp-*"
      - dependency-name: "frame-*"
      - dependency-name: "cumulus-*"
      - dependency-name: "parachain-info"
      - dependency-name: "pallet-*"
      - dependency-name: "xcm*"
      - dependency-name: "litentry-*"
      - dependency-name: "fork-tree"
      - dependency-name: "remote-externalities"
      - dependency-name: "beefy-*"
      - dependency-name: "try-runtime-*"
      - dependency-name: "test-runner"
      - dependency-name: "generate-bags"
    reviewers:
      - "Satoshi-Kusumoto"
      - "h4n0"
      - "suinuj"
      - "chenzongxiong"
      - "wangminqi"
      - "Kailai-Wang"
    schedule:
      interval: "weekly"
