name: Build docker with args

on:
  workflow_dispatch:
    inputs:
      docker_tag:
        description: The tag for the built docker image
        required: true
      args:
        description: Args to pass to `cargo build`, e.g. --features=runtime-benchmarks
        default: ''
        required: false


jobs:
  ## build docker image of client binary with args ##
  build-docker-with-args:
    runs-on: self-hosted
    steps:
      - name: Checkout codes on ${{ github.ref }}
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build docker image
        run: |
          ./scripts/build-docker.sh ${{ github.event.inputs.docker_tag }} "${{ github.event.inputs.args }}"
          echo "============================="
          docker images

      - name: Push docker image
        run: |
          docker push litentry/litentry-parachain:${{ github.event.inputs.docker_tag }}

      - name: Remove dangling images if any
        run: |
          [ -z "$(docker images --filter=dangling=true -q)" ] || docker rmi -f $(docker images --filter=dangling=true -q)

      - name: Copy client binary to disk
        run: |
          docker cp $(docker create --rm litentry/litentry-parachain:${{ github.event.inputs.docker_tag }}):/usr/local/bin/litentry-collator .

      - name: Upload the client binary
        uses: actions/upload-artifact@v2
        with:
          name: litentry-collator
          path: |
            litentry-collator
