name: Build & Test

on:
  push:
    branches: [ dev, dev_token_info_event ]
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-test:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Add wasm toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-03-24
        target: wasm32-unknown-unknown
        override: true
    - name: Build relay node and parachain
      run: |
        cargo build --release
        cd polkadot
        cargo build --release
        cd ..
    - name: Build token server
      run: |
        cd token-server
        cargo build --release
        cd ..

    - name: Set tmp directory
      id: set-tmpdir
      run: |
        tmpdir=$(mktemp -d /tmp/tmp.XXXXXX)
        echo "::set-output name=tmpdir::$tmpdir"

    - name: Run integration test
      run: |
        tmpdir=${{ steps.set-tmpdir.outputs.tmpdir }}
        ts-tests/scripts/run-test.sh $tmpdir

    - uses: actions/upload-artifact@v2
      if: ${{ failure() }}
      with:
        name: litentry-parachain-debug.log
        path: ${{ steps.set-tmpdir.outputs.tmpdir }}/**/*
        retention-days: 7

    - name: Clean up
      if: ${{ always() }}
      run: |
        tmpdir=${{ steps.set-tmpdir.outputs.tmpdir }}
        ts-tests/scripts/clean-up.sh $tmpdir
        rm -rf "$tmpdir"
      shell: bash {0}
