name: Build wasm

on:
  workflow_dispatch:
    inputs:
      ref:
        description: The ref to be used for the repo
        default: ''
        required: false

env:
  CARGO_TERM_COLOR: always

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes on ${{ github.event.inputs.ref || github.ref }}
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.ref || github.ref }}
          fetch-depth: 0

      - name: Build with srtool
        id: srtool_build
        uses: chevdor/srtool-actions@v0.3.0
        with:
          chain: litentry-parachain
          runtime_dir: runtime

      - name: Summary
        run: |
          echo '${{ steps.srtool_build.outputs.json }}' | jq . > litentry-parachain-srtool-digest.json
          echo "==============================================="
          cat litentry-parachain-srtool-digest.json
          cp ${{ steps.srtool_build.outputs.wasm }} litentry-parachain-runtime.compact.wasm
          cp ${{ steps.srtool_build.outputs.wasm_compressed }} litentry-parachain-runtime.compact.compressed.wasm

      - name: Upload wasm artefacts
        uses: actions/upload-artifact@v2
        with:
          name: litentry-parachain-runtime
          path: |
            litentry-parachain-srtool-digest.json
            litentry-parachain-runtime.compact.wasm
            litentry-parachain-runtime.compact.compressed.wasm
